.PHONY: all test clean sub_test sub_test_clean lib

CFLAGS += -std=c17 -O3 -Wall -pedantic -Werror -I..

all: test

sub_test:
	@$(MAKE) --directory=tests

sub_test_clean:
	@$(MAKE) --directory=tests clean

