vpath marked-files-in.% ../marked-files-in
vpath libmarked-files-in.a ../marked-files-in

libmarked-files-in.a: marked-files-in.o

include ../marked-files-in/marked-files-in.d

LIBS += libmarked-files-in.a
