vpath marked-files-in.% ../marked-files-in
vpath libmarked-files-in.a ../marked-files-in

libmarked-files-in.a: marked-files-in.o

marked-files-in.h: log.h
marked-files-in.o: marked-files-in.h

LIBS_H += marked-files-in.h
LIBS_O += libmarked-files-in.a
