DIR := ../marked-files-in
LIB := libmarked-files-in.a
FULL_LIB := $(DIR)/$(LIB)


$(FULL_LIB): $(DIR)/marked-files-in.h $(DIR)/marked-files-in.cpp ../log/log.h
	$(MAKE) -C $(DIR) lib

LIBS += $(FULL_LIB)
