include ../Makefile.base
include ../log/Makefile.lib
include ../marked-files-in/Makefile.lib
include ../marked-files-out/Makefile.lib
include Makefile.lib

test: libta.a
	# done

clean:
	$(RM) libta.a ta.o
